// src/lib/gemini.ts
// Helper service for generating lesson plans using Google Gemini AI

import { GoogleGenerativeAI } from '@google/generative-ai'

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY as string

export interface LessonPlanInput {
  topic: string
  bullets: string[]          // key objectives / bullet points
  subject: string            // e.g. "Mathematics"
  className: string          // e.g. "Class 8B"
  gradeLevel?: string        // optional hint for depth
}

export interface GeneratedLessonPlan {
  markdown: string           // fully rendered Markdown plan
  generatedAt: string        // ISO timestamp
  topic: string
  subject: string
}

// Model fallback chain — tries each in order until one succeeds
const MODEL_CHAIN = [
  'gemini-2.0-flash-lite',
  'gemini-1.5-flash-latest',
  'gemini-2.0-flash',
]

/**
 * Generates a detailed lesson plan. Tries models in fallback order
 * so a quota error on one model automatically retries with the next.
 */
export async function generateLessonPlan(input: LessonPlanInput): Promise<GeneratedLessonPlan> {
  if (!API_KEY) throw new Error('VITE_GEMINI_API_KEY is not set in your .env file.')

  const genAI = new GoogleGenerativeAI(API_KEY)

  const bulletsText = input.bullets.filter(b => b.trim()).map(b => `- ${b}`).join('\n')

  const prompt = `
You are an expert curriculum designer helping a teacher create a detailed lesson plan.

**Subject:** ${input.subject}
**Class / Grade:** ${input.className}${input.gradeLevel ? ` (${input.gradeLevel})` : ''}
**Topic:** ${input.topic}

**Key Objectives / Bullets from the teacher:**
${bulletsText || '- (teacher did not specify — use the topic to infer objectives)'}

---

Please generate a **comprehensive, well-structured lesson plan** in Markdown format following this exact structure:

# 📚 Lesson Plan: [Topic Name]

## 📋 Overview
| Field | Detail |
|-------|--------|
| Subject | ${input.subject} |
| Class | ${input.className} |
| Topic | [topic] |
| Duration | 40 minutes |
| Difficulty | [easy/medium/hard based on topic] |

## 🎯 Learning Objectives
By the end of this lesson, students will be able to:
1. [Objective 1]
2. [Objective 2]
3. [Objective 3]

## 🔑 Key Vocabulary
| Term | Definition |
|------|-----------|
| [term] | [simple definition] |

## 🖼️ Visual Aid
Include ONE relevant image using this EXACT format (choose a real, descriptive Unsplash or Wikimedia URL relevant to the topic):
![Description of image](https://source.unsplash.com/800x400/?[keyword1],[keyword2])

## 🏫 Lesson Structure

### 1. Introduction / Hook (5 minutes)
[Engaging opening activity or question]

### 2. Instruction / Direct Teaching (15 minutes)
[Clear, detailed explanation of the main concept. Use bullet points and sub-headings.]

### 3. Guided Practice (10 minutes)
[Activity where the teacher works through examples with students]

### 4. Independent Practice (8 minutes)
[Activity students do on their own]

### 5. Conclusion / Wrap-Up (2 minutes)
[How to close the lesson and check for understanding]

## 📝 Assessment
- **Formative:** [Quick check method during class]
- **Summative:** [Homework or test idea]

## 🏠 Homework Assignment
[Clear, achievable homework task]

## 📚 Additional Resources
- [Resource 1 with brief description]
- [Resource 2 with brief description]

## 💡 Teacher Tips
[2-3 practical tips for delivering this specific lesson well]

---
*Generated by World Uni-Learn AI Lesson Planner*

IMPORTANT RULES:
- Write in clear, professional English suitable for a teacher to use directly.
- The image URL must use the format: https://source.unsplash.com/800x400/?keyword
- Keep explanations detailed but accessible to the specified class level.
- Do NOT add any text before or after the Markdown — return ONLY the Markdown.
`.trim()

  let lastError: Error | null = null

  for (const modelName of MODEL_CHAIN) {
    try {
      const model = genAI.getGenerativeModel({ model: modelName })
      const result = await model.generateContent(prompt)
      const markdown = result.response.text()
      return {
        markdown,
        generatedAt: new Date().toISOString(),
        topic: input.topic,
        subject: input.subject,
      }
    } catch (err: any) {
      const is429 = err?.message?.includes('429') || err?.message?.includes('quota')
      const is404 = err?.message?.includes('404') || err?.message?.includes('not found')
      if (is429 || is404) {
        lastError = err
        continue // try next model
      }
      // For other errors (auth, network) fail immediately
      throw new Error(`AI Error: ${err.message ?? String(err)}`)
    }
  }

  // All models exhausted
  throw new Error(
    '⚠️ Your Gemini API key has exceeded its free quota for today. ' +
    'This resets every 24 hours — please try again tomorrow, or visit ' +
    'https://aistudio.google.com to check your usage. ' +
    `(Last error: ${lastError?.message?.slice(0, 120)})`
  )
}

