// src/lib/groq.ts
// Helper service for generating lesson plans using Groq (Llama 3)

const API_KEY = import.meta.env.VITE_GROQ_API_KEY as string
const MODEL = 'llama-3.3-70b-versatile'

export interface LessonPlanInput {
  topic: string
  bullets: string[]          // key objectives / bullet points
  subject: string            // e.g. "Mathematics"
  className: string          // e.g. "Class 8B"
  gradeLevel?: string        // optional hint for depth
}

export interface GeneratedLessonPlan {
  markdown: string           // fully rendered Markdown plan
  generatedAt: string        // ISO timestamp
  topic: string
  subject: string
}

/**
 * Generates a detailed lesson plan using Groq API.
 */
export async function generateLessonPlan(input: LessonPlanInput): Promise<GeneratedLessonPlan> {
  if (!API_KEY) {
    throw new Error('VITE_GROQ_API_KEY is not set in your .env file. Please add your Groq API key from console.groq.com to continue.')
  }

  const bulletsText = input.bullets.filter(b => b.trim()).map(b => `- ${b}`).join('\n')

  const prompt = `
You are an expert curriculum designer helping a teacher create a detailed lesson plan.

**Subject:** ${input.subject}
**Class / Grade:** ${input.className}${input.gradeLevel ? ` (${input.gradeLevel})` : ''}
**Topic:** ${input.topic}

**Key Objectives / Bullets from the teacher:**
${bulletsText || '- (teacher did not specify — use the topic to infer objectives)'}

---

Please generate a **comprehensive, well-structured lesson plan** in Markdown format following this exact structure:

# 📚 Lesson Plan: [Topic Name]

## 📋 Overview
| Field | Detail |
|-------|--------|
| Subject | ${input.subject} |
| Class | ${input.className} |
| Topic | [topic] |
| Duration | 40 minutes |
| Difficulty | [easy/medium/hard based on topic] |

## 🎯 Learning Objectives
By the end of this lesson, students will be able to:
1. [Objective 1]
2. [Objective 2]
3. [Objective 3]

## 🔑 Key Vocabulary
| Term | Definition |
|------|-----------|
| [term] | [simple definition] |

## 🖼️ Visual Aid
Include ONE relevant image using this EXACT format (choose a real, descriptive Unsplash or Wikimedia URL relevant to the topic):
![Description of image](https://source.unsplash.com/800x400/?[keyword1],[keyword2])

## 🏫 Lesson Structure

### 1. Introduction / Hook (5 minutes)
[Engaging opening activity or question]

### 2. Instruction / Direct Teaching (15 minutes)
[Clear, detailed explanation of the main concept. Use bullet points and sub-headings.]

### 3. Guided Practice (10 minutes)
[Activity where the teacher works through examples with students]

### 4. Independent Practice (8 minutes)
[Activity students do on their own]

### 5. Conclusion / Wrap-Up (2 minutes)
[How to close the lesson and check for understanding]

## 📝 Assessment
- **Formative:** [Quick check method during class]
- **Summative:** [Homework or test idea]

## 🏠 Homework Assignment
[Clear, achievable homework task]

## 📚 Additional Resources
- [Resource 1 with brief description]
- [Resource 2 with brief description]

## 💡 Teacher Tips
[2-3 practical tips for delivering this specific lesson well]

---
*Generated by Nexora AI Lesson Planner (Groq)*

IMPORTANT RULES:
- Write in clear, professional English suitable for a teacher to use directly.
- The image URL must use the format: https://source.unsplash.com/800x400/?keyword
- Keep explanations detailed but accessible to the specified class level.
- Do NOT add any text before or after the Markdown — return ONLY the Markdown.
`.trim()

  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: MODEL,
        messages: [
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 2048
      })
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(errorData.error?.message || `Groq API error: ${response.statusText}`)
    }

    const data = await response.json()
    const markdown = data.choices[0]?.message?.content || ''

    if (!markdown) throw new Error('No content received from Groq.')

    return {
      markdown: markdown.trim(),
      generatedAt: new Date().toISOString(),
      topic: input.topic,
      subject: input.subject,
    }
  } catch (err: any) {
    console.error('Groq Error:', err)
    throw new Error(`AI Error (Groq): ${err.message ?? String(err)}`)
  }
}

export interface GeneratedQuizContent {
  title: string
  description: string
  questions: any[]
}

/**
 * Generates a multiple choice quiz from provided text using Groq.
 */
export async function generateQuizFromText(text: string, count: number = 10): Promise<GeneratedQuizContent> {
  if (!API_KEY) throw new Error('VITE_GROQ_API_KEY is not set in your .env file.')

  const prompt = `You are an expert educational AI. Your task is to output exactly ${count} multiple choice questions in JSON format based on the text below.

IMPORTANT INSTRUCTIONS:
1. If the provided text already contains a list of questions (e.g. a past exam paper or quiz), you MUST EXTRACT those exact questions, their options, and determine the correct answers. Do not make up new questions if they are already provided in the text.
2. If the provided text is study material (e.g. a textbook chapter, syllabus, or notes), you must GENERATE ${count} new questions based on the facts in the text.
3. Return ONLY valid JSON matching this exact schema WITHOUT any markdown formatting blocks like \`\`\`json:

{
  "title": "Quiz Title",
  "description": "Quiz Description",
  "questions": [
    {
      "text": "The question text?",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correctAnswer": "The exact text of the correct option"
    }
  ]
}

Text to process:
${text}
`

  try {
    const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [{ role: 'user', content: prompt }],
        response_format: { type: "json_object" }
      })
    })

    if (!res.ok) {
      const err = await res.json()
      throw new Error(err.error?.message || "Failed to generate")
    }

    const data = await res.json()
    let textResponse = data.choices[0].message.content
    
    // Clean up markdown block if present
    if (textResponse.startsWith('\`\`\`json')) {
      textResponse = textResponse.replace(/^\`\`\`json/m, '').replace(/\`\`\`$/m, '').trim()
    } else if (textResponse.startsWith('\`\`\`')) {
      textResponse = textResponse.replace(/^\`\`\`/m, '').replace(/\`\`\`$/m, '').trim()
    }

    const parsed = JSON.parse(textResponse)
    
    return {
      title: parsed.title || 'AI Generated Quiz',
      description: parsed.description || '',
      questions: parsed.questions || []
    }
  } catch (err: any) {
    throw new Error(`AI Error: ${err.message ?? 'Failed to generate quiz.'}`)
  }
}

