// src/lib/huggingface.ts
// Helper service for generating lesson plans using Hugging Face Inference API
import { HfInference } from '@huggingface/inference'

const API_KEY = import.meta.env.VITE_HUGGINGFACE_API_KEY as string
const USER_MODEL = import.meta.env.VITE_HUGGINGFACE_MODEL

const MODEL_CHAIN = [
  USER_MODEL,
  'mistralai/Mistral-7B-Instruct-v0.3',
  'HuggingFaceH4/zephyr-7b-beta',
  'mistralai/Mistral-7B-Instruct-v0.2',
  'google/gemma-1.1-7b-it',
  'Qwen/Qwen2.5-7B-Instruct',
  'microsoft/Phi-3-mini-4k-instruct',
].filter(Boolean) as string[]

export interface LessonPlanInput {
  topic: string
  bullets: string[]          // key objectives / bullet points
  subject: string            // e.g. "Mathematics"
  className: string          // e.g. "Class 8B"
  gradeLevel?: string        // optional hint for depth
}

export interface GeneratedLessonPlan {
  markdown: string           // fully rendered Markdown plan
  generatedAt: string        // ISO timestamp
  topic: string
  subject: string
}

/**
 * Generates a detailed lesson plan using Hugging Face Inference API.
 */
export async function generateLessonPlan(input: LessonPlanInput): Promise<GeneratedLessonPlan> {
  if (!API_KEY) {
    throw new Error('VITE_HUGGINGFACE_API_KEY is not set in your .env file. Please add your Hugging Face API key to continue.')
  }

  const hf = new HfInference(API_KEY)

  const bulletsText = input.bullets.filter(b => b.trim()).map(b => `- ${b}`).join('\n')

  const prompt = `You are an expert curriculum designer helping a teacher create a detailed lesson plan.

Subject: ${input.subject}
Class / Grade: ${input.className}${input.gradeLevel ? ` (${input.gradeLevel})` : ''}
Topic: ${input.topic}

Key Objectives / Bullets from the teacher:
${bulletsText || '- (teacher did not specify — use the topic to infer objectives)'}

Please generate a comprehensive, well-structured lesson plan in Markdown format following this exact structure:

# 📚 Lesson Plan: [Topic Name]

## 📋 Overview
| Field | Detail |
|-------|--------|
| Subject | ${input.subject} |
| Class | ${input.className} |
| Topic | [topic] |
| Duration | 40 minutes |
| Difficulty | [easy/medium/hard based on topic] |

## 🎯 Learning Objectives
By the end of this lesson, students will be able to:
1. [Objective 1]
2. [Objective 2]
3. [Objective 3]

## 🔑 Key Vocabulary
| Term | Definition |
|------|-----------|
| [term] | [simple definition] |

## 🖼️ Visual Aid
Include ONE relevant image using this EXACT format (choose a real, descriptive Unsplash URL relevant to the topic):
![Description of image](https://source.unsplash.com/800x400/?[keyword1],[keyword2])

## 🏫 Lesson Structure

### 1. Introduction / Hook (5 minutes)
[Engaging opening activity or question]

### 2. Instruction / Direct Teaching (15 minutes)
[Clear, detailed explanation of the main concept. Use bullet points and sub-headings.]

### 3. Guided Practice (10 minutes)
[Activity where the teacher works through examples with students]

### 4. Independent Practice (8 minutes)
[Activity students do on their own]

### 5. Conclusion / Wrap-Up (2 minutes)
[How to close the lesson and check for understanding]

## 📝 Assessment
- Formative: [Quick check method during class]
- Summative: [Homework or test idea]

## 🏠 Homework Assignment
[Clear, achievable homework task]

## 📚 Additional Resources
- [Resource 1 with brief description]
- [Resource 2 with brief description]

## 💡 Teacher Tips
[2-3 practical tips for delivering this specific lesson well]

---
*Generated by World Uni-Learn AI Lesson Planner (Hugging Face)*

IMPORTANT RULES:
- Write in clear, professional English suitable for a teacher to use directly.
- The image URL must use the format: https://source.unsplash.com/800x400/?keyword
- Keep explanations detailed but accessible to the specified class level.
- Do NOT add any text before or after the Markdown — return ONLY the Markdown.`.trim()

  let lastError: any = null

  for (const modelName of MODEL_CHAIN) {
    try {
      // Using chatCompletion as many modern Instruct models are optimized for the 'conversational' task
      const response = await hf.chatCompletion({
        model: modelName,
        messages: [
          { role: 'user', content: prompt }
        ],
        max_tokens: 2048,
        temperature: 0.7,
        top_p: 0.9,
      })

      const markdown = response.choices[0].message.content || ''
      if (!markdown) continue

      return {
        markdown: markdown.trim(),
        generatedAt: new Date().toISOString(),
        topic: input.topic,
        subject: input.subject,
      }
    } catch (err: any) {
      lastError = err
      console.warn(`Hugging Face model ${modelName} failed, trying next...`, err.message)
      
      // If it's a quota or auth error, don't bother retrying others as they share the same key/limit
      if (err.message?.includes('401') || err.message?.includes('429')) {
        break
      }
      continue
    }
  }

  // All models exhausted
  console.error('All Hugging Face models failed:', lastError)
  
  if (lastError?.message?.includes('Failed to perform inference') || lastError?.message?.includes('HTTP error')) {
    throw new Error('⚠️ Hugging Face Provider Error: The AI service is currently experiencing high load. Please wait 1 minute and try again, or check your API key status.')
  }

  throw new Error(`AI Error (Hugging Face): ${lastError?.message ?? String(lastError)}`)
}
