// src/constants/routes.ts
export const ROUTES = {
  // Auth
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',

  // Admin
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_STUDENTS: '/admin/students',
  ADMIN_TEACHERS: '/admin/teachers',
  ADMIN_OTHER_STAFF: '/admin/other-staff',
  ADMIN_CLASSES: '/admin/classes',
  ADMIN_SUBJECTS: '/admin/subjects',
  ADMIN_DEPARTMENTS: '/admin/departments',
  ADMIN_ACADEMIC_YEARS: '/admin/academic-years',
  ADMIN_TERMS: '/admin/terms',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_PERFORMANCE: '/admin/performance',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_TIMETABLE: '/admin/timetable',
  ADMIN_ANNOUNCEMENTS: '/admin/announcements',
  ADMIN_SYLLABUS: '/admin/syllabus',
  ADMIN_WEEKLY_GOALS: '/admin/weekly-goals',
  ADMIN_ATTENDANCE: '/admin/attendance',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_AGENDA: '/admin/agenda',
  ADMIN_SMS: '/admin/sms',
  ADMIN_ADMISSIONS: '/admin/admissions',
  ADMIN_BURSARS: '/admin/bursars',
  ADMIN_TEST_ANALYTICS: '/admin/test-analytics',
  ADMIN_VISITORS: '/admin/visitors',
  ADMIN_PROMOTION: '/admin/promotion',
  ADMIN_ALUMNI: '/admin/alumni',
  ADMIN_CALENDAR: '/admin/calendar',

  // Teacher
  TEACHER_DASHBOARD: '/teacher/dashboard',
  TEACHER_MY_CLASSES: '/teacher/my-classes',
  TEACHER_SCORE_ENTRY: '/teacher/score-entry',
  TEACHER_REPORTS: '/teacher/reports',
  TEACHER_TIMETABLE: '/teacher/timetable',
  TEACHER_NOTIFICATIONS: '/teacher/notifications',
  TEACHER_SYLLABUS: '/teacher/syllabus',
  TEACHER_LESSON_TRACKER: '/teacher/lesson-tracker',
  TEACHER_STUDENTS: '/teacher/students',
  TEACHER_ASSIGNMENTS: '/teacher/assignments',
  TEACHER_SUBJECTS: '/teacher/subjects',
  TEACHER_ATTENDANCE: '/teacher/attendance',
  TEACHER_MESSAGES: '/teacher/messages',
  TEACHER_AGENDA: '/teacher/agenda',
  TEACHER_TYPING_GAME: '/teacher/typing-game',
  TEACHER_CLASS_TESTS: '/teacher/class-tests',

  // Student
  STUDENT_DASHBOARD: '/student/dashboard',
  STUDENT_ASSIGNMENTS: '/student/assignments',
  STUDENT_RESULTS: '/student/results',
  STUDENT_SCHEDULE: '/student/schedule',
  STUDENT_TYPING_GAME: '/student/typing-game',
  STUDENT_LIBRARY: '/student/library',
  STUDENT_BILLING: '/student/billing',
  STUDENT_RESOURCES: '/student/resources',
  STUDENT_PROFILE: '/student/profile',
  STUDENT_ATTENDANCE: '/student/attendance',
  STUDENT_ANNOUNCEMENTS: '/student/announcements',
  STUDENT_CALENDAR: '/student/calendar',
  STUDENT_SUBJECTS: '/student/subjects',
  STUDENT_ELECTIONS: '/student/elections',

  // Bursar
  BURSAR_DASHBOARD:  '/bursar/dashboard',
  BURSAR_FEES:       '/bursar/fees',
  BURSAR_DEBTORS:    '/bursar/debtors',
  BURSAR_PAYROLL:    '/bursar/payroll',
  BURSAR_INCOME:     '/bursar/income',
  BURSAR_EXPENSES:   '/bursar/expenses',
  BURSAR_ANALYTICS:  '/bursar/analytics',
  BURSAR_BILL_SHEET: '/bursar/bill-sheet',
  BURSAR_REPORTS:    '/bursar/reports',
  BURSAR_INVENTORY:  '/bursar/inventory',
  BURSAR_STUDENTS:   '/bursar/students',
  BURSAR_SMS:        '/bursar/sms',

  // Other Staff
  STAFF_DASHBOARD: '/staff/dashboard',

  // Super Admin
  SUPER_ADMIN_DASHBOARD: '/super-admin/dashboard',
  SUPER_ADMIN_SCHOOLS: '/super-admin/schools',
  SUPER_ADMIN_QUIZZES: '/super-admin/quizzes',
  SUPER_ADMIN_MESSAGING: '/super-admin/messaging',
  SUPER_ADMIN_ANALYTICS: '/super-admin/analytics',
  SUPER_ADMIN_RESOURCES: '/super-admin/resources',
  SUPER_ADMIN_SUBJECTS: '/super-admin/subjects',
  SUPER_ADMIN_MESSAGES: '/super-admin/messaging',
} as const